import './globals.css'
import { IBM_Plex_Sans } from 'next/font/google'
import { type ReactNode } from 'react'

const font = IBM_Plex_Sans({ subsets: ['latin-ext'], weight: '600' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: ReactNode }): ReactNode {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
